export const NEW_PROJECT = 'PROJECTS/NEW_PROJECT'
export const SUCCESS = 'PROJECTS/SUCCESS'
export const NAME_PROJECT = 'PROJECTS/NAME_PROJECT'
export const SHOW_PROJECT = 'PROJECTS/SHOW_PROJECT'
export const SHOW_ALERT = 'PROJECTS/SHOW_ALERT'
export const HIDE_ALERT = 'PROJECTS/HIDE_ALERT'
export const FLAG_DELETE = 'PROJECTS/FLAG_DELETE'

export const REQUESTED_SUCCEEDED_PROJECT = 'PROJECTS/REQUESTED_SUCCEEDED_PROJECT'
export const REQUESTED_PROJECT = 'PROJECTS/REQUESTED_PROJECT'
export const REQUESTED_FAILED_PROJECT = 'PROJECTS/REQUESTED_FAILED_PROJECT'
export const REQUESTED_SUCCEEDED_CLOSE_PROJECT = 'PROJECTS/REQUESTED_SUCCEEDED_CLOSE_PROJECT'

export const REQUESTED_SUCCEEDED_USER = 'PROJECTS/REQUESTED_SUCCEEDED_USER'
export const REQUESTED_USER = 'PROJECTS/REQUESTED_USER'
export const REQUESTED_FAILED_USER = 'PROJECTS/REQUESTED_FAILED_USER'
export const REQUESTED_SUCCEEDED_CLOSE_USER = 'PROJECTS/REQUESTED_SUCCEEDED_CLOSE_USER'

export const IS_AUTH = 'USERS/IS_AUTH'
export const USER_ID = 'USERS/USER_ID'
export const USER_NAME = 'USERS/USER_NAME'
export const USER_SURNAME = 'USERS/USER_SURNAME'

export const USER_COUNT_PROJECT = 'USERS/USER_COUNT_PROJECT'

export const USER_SEX = 'USERS/USER_SEX'
export const USER_AGE = 'USERS/USER_AGE'
export const USER_COUNTRY = 'USERS/USER_COUNTRY'
export const USER_PHONE = 'USERS/USER_PHONE'

export const USER_EMAIL = 'USERS/USER_EMAIL'
export const USER_PASSWORD = 'USERS/USER_PASSWORD'
export const USER_ROLE = 'USERS/USER_ROLE'
export const CLEAR_USER = 'USERS/CLEAR_USER'
export const SHOW_ALERT_USER = 'PROJECTS/SHOW_ALERT'
export const HIDE_ALERT_USER = 'PROJECTS/HIDE_ALERT'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'


export const CHANGE = 'USERS/CHANGE'
export const ERROR = 'USERS/ERROR'
export const FLAG = 'USERS/FLAG'